---
# ───────────────────────────── ①  導入モード (deploy_state=present) ─────────────────────────────
- name: Install stack when deploy_state=present
  hosts: exporter_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'present' }}"
  roles:
    - { role: podman_engine,       when: apply }      # ① 先に podman
    - { role: postgres_exporter,   when: apply }      # ② その上に Exporter

# ───────────────────────────── ②  撤去モード (deploy_state=absent) ─────────────────────────────
- name: Remove stack when deploy_state=absent
  hosts: exporter_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'absent' }}"
  roles:
    - { role: postgres_exporter,   when: apply }      # ① Exporter を削除
    - { role: podman_engine,       when: apply }      # ② 最後に Podman をアンインストール
