---
# ───────────────────────────── ①  導入モード (deploy_state=present) ─────────────────────────────
- name: Install stack when deploy_state=present
  hosts: postgres_main_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'present' }}"
  roles:
    - { role: postgres_exporter_user,       when: apply }

- name: Install stack when deploy_state=present
  hosts: postgres_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'present' }}"
  roles:
    - { role: postgres_exporter_access,       when: apply }

# ───────────────────────────── ②  撤去モード (deploy_state=absent) ─────────────────────────────
- name: Remove stack when deploy_state=absent
  hosts: postgres_main_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'absent' }}"
  roles:
  
- name: Remove stack when deploy_state=absent
  hosts: postgres_host
  become: true
  vars:
    apply: "{{ deploy_state | default('present') == 'absent' }}"
  roles:
    - { role: postgres_exporter_access,       when: apply }
