- name: ポートリストを準備する
  set_fact:
    ports_list: "{{ pg_exporter_ports | default([pg_exporter_port]) }}"

- name: 各ポートに対してメトリクスを取得する
  uri:
    url: "http://{{ pg_exporter_host }}:{{ item_port }}/metrics"
    method: GET
    return_content: yes
    status_code: 200
    timeout: 5
  register: metrics_results
  no_log: true
  loop: "{{ ports_list }}"
  loop_control:
    loop_var: item_port

- name: 各ポートの pg_up を検証する（複数ポート時のみ）
  when: ports_list | length > 1
  include_tasks: check_pgup.yml
  loop: "{{ metrics_results.results }}"
  loop_control:
    loop_var: metrics