
- name: PostgreSQL用pythonライブラリをインストール (Debian系)
  apt:
    name: python3-psycopg2
    state: present
  when: ansible_os_family == 'Debian'

- name: PostgreSQL用pythonライブラリをインストール (RHEL系)
  dnf:
    name: python3-psycopg2
    state: present
  when: ansible_os_family == 'RedHat'

- block:
    - name: exporter_user 作成または削除
      community.postgresql.postgresql_user:
        name: "{{ pg_user }}"
        password: "{{ pgexp_pass }}"
        db: postgres
        state: "{{ deploy_state }}"
        encrypted: true
      become_user: postgres

    - name: exporter_userのpg_monitorロール付与または削除
      community.postgresql.postgresql_membership:
        group: pg_monitor
        target_roles: "{{ pg_user }}"
        state: "{{ deploy_state }}"
      become_user: postgres
      when: deploy_state == 'present'

  rescue:
    - name: エラー時の通知
      debug:
        msg: "エラーが発生しました。"