###############################################################################
# deploy_state=present のときだけ実行 ───────────────────────────────────────────
###############################################################################
- block:
    - name: DNF キャッシュをクリア
      ansible.builtin.command: dnf clean all
      when: deploy_state == 'present'

    - name: DNF メタデータを更新
      ansible.builtin.command: dnf makecache
      when: deploy_state == 'present'

    # ── dnf-plugins-core（config-manager 用）
    - name: dnf-plugins-core をインストール
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    # ── AlmaLinux9 で必要なリポジトリを有効化
    - name: CRB リポジトリを有効化（slirp4netns 用）
      ansible.builtin.command: dnf config-manager --set-enabled crb

    - name: Extras リポジトリを有効化（container-selinux 用）
      ansible.builtin.command: dnf config-manager --set-enabled extras

    - name: Install podman & sops
      dnf:
        name:
          - podman
          - slirp4netns
          - fuse-overlayfs
          - container-selinux
          - sops
          - podman-docker        # docker コマンド互換が不要なら削除
        state: present
        allowerasing: true

    - name: Enable podman.socket (optional)
      service:
        name: podman.socket
        state: started
        enabled: true
      when: podman_enable_socket

  when:
    - deploy_state == 'present'
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version | int == 9

###############################################################################
# deploy_state=absent のときだけ実行 ───────────────────────────────────────────
###############################################################################
- block:
    # ── Podman & sops を削除
    - name: Remove Podman stack & sops
      ansible.builtin.dnf:
        name:
          - podman
          - slirp4netns
          - fuse-overlayfs
          - container-selinux
          - sops
          - podman-docker        # docker コマンド互換が不要なら削除
        state: absent

    # ── podman.socket を停止
    - name: Stop & disable podman.socket
      ansible.builtin.service:
        name: podman.socket
        state: stopped
        enabled: false
      ignore_errors: true

  when:
    - deploy_state == 'absent'
    - ansible_distribution == "AlmaLinux"
    - ansible_distribution_major_version | int == 9
